"""initial migration

Revision ID: 8b896f8ccad2
Revises: 
Create Date: 2026-04-07 15:59:35.915162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b896f8ccad2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_tag')
    op.drop_table('applicant_review')
    op.drop_table('applicant_tag')
    with op.batch_alter_table('applicant_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_file', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('portfolio_file', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('certificate_files', sa.Text(), nullable=True))

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('remarks')
        batch_op.drop_column('rating')
        batch_op.drop_column('recruiter_tags')

    with op.batch_alter_table('hr_feedback', schema=None) as batch_op:
        batch_op.drop_column('tags')

    with op.batch_alter_table('hr_notification', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'])

    with op.batch_alter_table('hr_profile', schema=None) as batch_op:
        batch_op.alter_column('headline',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('linkedin',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('github',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('portfolio',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('arrangement',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('experience_level',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('years_exp',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('education',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('languages',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'message', ['reply_to_id'], ['id'])

    with op.batch_alter_table('recruiter_notification', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'])

    with op.batch_alter_table('recruiter_profile', schema=None) as batch_op:
        batch_op.alter_column('headline',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('linkedin',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('github',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('portfolio',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('recruiter_profile', schema=None) as batch_op:
        batch_op.alter_column('portfolio',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('github',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('linkedin',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('headline',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('recruiter_notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('languages',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('education',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('years_exp',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('experience_level',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('arrangement',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('hr_profile', schema=None) as batch_op:
        batch_op.alter_column('portfolio',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('github',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('linkedin',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('headline',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('hr_notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('hr_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', mysql.VARCHAR(length=300), nullable=True))

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recruiter_tags', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remarks', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('applicant_profile', schema=None) as batch_op:
        batch_op.drop_column('certificate_files')
        batch_op.drop_column('portfolio_file')
        batch_op.drop_column('resume_file')

    op.create_table('applicant_tag',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('application_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('added_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], name=op.f('applicant_tag_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name=op.f('applicant_tag_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applicant_review',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('application_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('review', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name=op.f('applicant_review_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], name=op.f('applicant_review_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('application_tag',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('application_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reviewer_role', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('tag', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name=op.f('application_tag_ibfk_1')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], name=op.f('application_tag_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
