"""add applicant notifications

Revision ID: fffa6a17b367
Revises: 8b896f8ccad2
Create Date: 2026-04-08 18:16:08.713797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fffa6a17b367'
down_revision = '8b896f8ccad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicant_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('applicant_notification_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'])
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicant_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('applicant_notification_ibfk_3'), 'user', ['sender_id'], ['id'])
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
